#!/bin/sh

echo "GENERAL SYSTEM INFORMATION\n"
/usr/bin/figlet $(hostname)
echo
/usr/bin/neofetch

echo
echo "---------------------------------------------------"
echo "|  Server Responsible: Ufficio CybInt - Sez. ATSC |"
echo "|  Contact Number: 2028825                        |"
echo "---------------------------------------------------\n"
echo
echo " ******************************************************************"
echo " * WARNING: Unauthorized access to this system is prohibited.     *"
echo " * All activities on this system are logged.                      *"
echo " * By accessing this system, you consent to monitoring.           *"
echo " * Unauthorized access will be prosecuted to the fullest extent   *"
echo " * of the law.                                                    *"
echo " ******************************************************************"
echo
